/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Canios_Banco: THREE.Mesh
    Cubiculo_Banco: THREE.Mesh
    Mesa_Banco: THREE.Mesh
    Canios_Silla: THREE.Mesh
    Silla: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function SchoolTable(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/school_table.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canios_Banco.geometry}
        material={nodes.Canios_Banco.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cubiculo_Banco.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesa_Banco.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canios_Silla.geometry}
        material={nodes.Canios_Silla.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Silla.geometry}
        material={nodes.Silla.material}
      />
    </group>
  )
}

useGLTF.preload('/school_table.glb')
