/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Espada: THREE.Mesh
  }
  materials: Record<string, never>
}

export function Sword(props: React.ComponentProps<'group'>) {
  const { nodes } = useGLTF('/models/sword.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Espada.geometry}
        material={nodes.Espada.material}
      />
    </group>
  )
}

useGLTF.preload('/sword.glb')
